/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 0588350abbb82f70ebe13bb57f6b9415)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "ReliabilityAgent" | "CostAgent" | "UXAgent" | "DebateCoordinator";
	}
	interface Env {
		OPENAI_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		ReliabilityAgent: DurableObjectNamespace<import("./src/server").ReliabilityAgent>;
		CostAgent: DurableObjectNamespace<import("./src/server").CostAgent>;
		UXAgent: DurableObjectNamespace<import("./src/server").UXAgent>;
		DebateCoordinator: DurableObjectNamespace<import("./src/server").DebateCoordinator>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
